name 'cesnet-impala'
version '1.2.0'
source 'https://github.com/MetaCenterCloudPuppet/cesnet-impala'
author 'Frantisek Dvorak <valtri@civ.zcu.cz>'
license 'MIT'
summary 'Cloudera Impala Puppet Module'
description 'Cloudera Impala Puppet Module'
project_page 'https://github.com/MetaCenterCloudPuppet/cesnet-impala'

dependency 'puppetlabs/stdlib', '>=1.0.0 <5.0.0'
dependency 'cesnet/hadoop_lib', '<1.0.0'
